#!/usr/bin/env bash
set -e
set -u
set -E # let shell functions inherit ERR trap
trap err_handler 1 2 3 15 ERR

function err_handler {
  local exit_status=${1:-$?}
  logger -s -p "syslog.err" -t "server-fw.deb" "prerm script '$0' error code $exit_status (line $BASH_LINENO: '$BASH_COMMAND')"
  exit $exit_status
}

if [ $(ps -ef|grep -v grep|grep sbin\/server-fw|wc -l) -ne 0 ]; then
  service server-fw stop 
  sleep 1
fi 

exit 0
